name: "Azure Machine Learning Deploy Action"
description: "Deploy a registered model in your Azure Machine Learning Workspace with this GitHub Action"
author: "azure/gh-aml"
inputs:
  azure_credentials:
    description: "Paste output of `az ad sp create-for-rbac --name <your-sp-name> --role contributor --scopes /subscriptions/<your-subscriptionId>/resourceGroups/<your-rg> --sdk-auth` as value of secret variable: AZURE_CREDENTIALS"
    required: true
  model_name:
    description: "Name of the model that will be deployed"
    required: true
  model_version:
    description: "Version of the model that will be deployed"
    required: true
  parameters_file:
    description: "JSON file including the parameters for deployment. This looks in the .ml/.azure/ directory"
    required: true
    default: "deploy.json"
outputs:
  service_scoring_uri:
    description: "Scoring URI of the webservice that was created (only provided if delete_service_after_deployment is set to False)"
  service_swagger_uri:
    description: "Swagger URI of the webservice that was created (only provided if delete_service_after_deployment is set to False)"
  acr_address:
    description: "The DNS name or IP address (e.g. myacr.azurecr.io) of the Azure Container Registry (ACR) (only provided if create_image is not None)"
  acr_username:
    description: "The username for ACR (only provided if create_image is not None)"
  acr_password:
    description: "The password for ACR (only provided if create_image is not None)"
  package_location:
    description: "Full URI of the docker image (e.g. myacr.azurecr.io/azureml/azureml_*) (only provided if create_image is not None)"
  profiling_details:
    description: "Dictionary of details of the model profiling result. This will only be provided, if the model profiling method is used and successfully executed."
branding:
  icon: "chevron-up"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
