name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
    
      # connect to existing workspace
      - name: Create Workspace
        id: ws_create
        uses: Azure/aml-workspace@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_workspace.json"

      # Deploy model in Azure Machine Learning to ACI
      - name: Deploy model
        id: aml_deploy
        uses: ./
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
            model_name:  mymodel
            model_version: 1
            parameters_file: "test/test_deploy.json"
