name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
      
      - name: Self test
        id: selftest
        uses: azure/aml-deploy@master
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
        continue-on-error: true
