
name: Function App Integration Test
on: [push , pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
      
      # Connect to existing workspace
      - name: Create Workspace
        id: ws_create
        uses: Azure/aml-workspace@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "test/test_workspace.json"

      # Deploy model in Azure Machine Learning to ACI
      - name: Deploy model
        id: aml_deploy
        uses: ./
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
            model_name:  mymodel
            model_version: 1
            parameters_file: "test/test_fapp_deploy.json"
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Container Action'
        uses: Azure/functions-container-action@v1
        id: fa
        with:
          app-name: amltest
          image: ${{ steps.aml_deploy.outputs.package_location }}
      
      - name: 'use the published functionapp url in upcoming steps'
        run: |
          echo "${{ steps.fa.outputs.app-url }}"
